#!/usr/bin/env node
import {mkdir,readFile,writeFile,copyFile,rm} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {createHash} from 'node:crypto';
import {publishReport} from '../../src/demo/report.mjs';
const root=new URL('../../',import.meta.url);
const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let out,created=false;
try {
 const args=process.argv.slice(2);
 if(args.length!==2||args[0]!=='--out'||!args[1]||/[\x00-\x1f\x7f]/.test(args[1]))throw Error('ARGUMENTS');
 out=resolve(args[1]);await mkdir(dirname(out),{recursive:true});await mkdir(out);created=true;
 const demo=join(out,'demo');await mkdir(demo);
 const s=await publishReport(new URL('planning/phase6/evidence/rehearsal/proof',root).pathname,demo);
 await copyFile(new URL('planning/phase0/fixtures/regime.graphql',root),join(out,'shared-query.graphql'));
 await copyFile(new URL('submission/ethonline2026/RECORDING.md',root),join(out,'RECORDING.md'));
 const txs=JSON.parse(await readFile(join(demo,'proof/transactions.json'),'utf8'));
 const txLink=(hash,label='Inspect receipt')=>{
  const tx=txs.find(x=>x.hash===hash);if(!tx)throw Error('RECEIPT');
  return `<details><summary>${escape(label)} · block ${escape(tx.blockNumber)} · ${escape(tx.status)}</summary><pre>${escape(JSON.stringify(tx,null,2))}</pre></details>`;
 };
 const metric=(label,value)=>`<div class="metric"><small>${escape(label)}</small><strong>${escape(value)}</strong></div>`;
 const panels=[
  `<h1>Inventory-aware liquidity.<br>Hard execution limits.</h1><p class="lead">A controlled treasury workflow on Aqua / SwapVM.</p><div class="metrics">${metric('Allocated WETH',s.start.weth+' WETH')}${metric('Allocated USDC',s.start.usdc+' USDC')}${metric('WETH exposure',s.start.wethPercent+'%')}</div><div class="range"><span>30% minimum</span><b>50% target</b><span>70% maximum</span></div><p>Valuation is fixed at 2,000 USDC / WETH. Inventory is allocated to one strategy; assets remain in the maker wallet.</p>`,
  `<h1>Two protocols.<br>One standardized query.</h1><p class="lead">Shared Messari schema → one normalizer → bounded tuning.</p><div class="metrics">${s.updates[0].sources.map(o=>`<div class="metric"><small>${escape(o.venue)}</small><code>${escape(o.deploymentCid)}</code><p>Volume: ${escape(o.dailyVolumeUsd)} USD</p></div>`).join('')}</div><p>Completed UTC day: ${escape(s.updates[0].sources[0].windowStart)} → ${escape(s.updates[0].sources[0].windowEnd)}</p><p>Intensity ${s.updates[0].intensityBps} bps · Spread ${s.updates[0].spreadBps} bps. Daily volume / 24 is an average-hour signal, not a current-hour snapshot.</p><p><a href="shared-query.graphql">Open the shared query</a> · <a href="demo/proof/graph.json">Raw and normalized observations</a></p>${txLink(s.updates[0].transactionHash,'Actual tuning update')}`,
  `<h1>A safe fill settles.<br>An unsafe fill reverts.</h1><div class="metrics">${s.attempts.slice(0,2).map(a=>`<div class="metric"><small>${escape(a.title)}</small><strong class="${a.reason?'warn':'good'}">${escape(a.outcome)}</strong><p>Input ${escape(a.input)}<br>Output ${escape(a.output??'None — reverted')}</p><p>${escape(a.before.wethPercent)}% → ${escape(a.after.wethPercent)}% WETH</p>${a.reason?'<code>'+escape(a.reason)+'</code>':''}${txLink(a.transactionHash)}</div>`).join('')}</div><p><a href="demo/proof/scenarios.json">Before/after token balances and allocation evidence</a></p>`,
  `<h1>Failures and recovery.<br>One continuous epoch.</h1><table><thead><tr><th>Attempt</th><th>Outcome</th><th>Exposure after</th></tr></thead><tbody>${s.attempts.map(a=>`<tr><td>${escape(a.title)}</td><td class="${a.reason?'warn':'good'}">${escape(a.reason??a.outcome)}</td><td>${escape(a.after.wethPercent)}%</td></tr>`).join('')}</tbody></table><p>Every rejected attempt preserves token and protected strategy state. Gas is outside allocation accounting.</p>${txLink(s.attempts.at(-1).transactionHash,'Resumed guarded fill')}`,
  `<h1>Business permissions.<br>Actual enforcement.</h1><div class="metrics">${metric('Owner authorization','2 of 3 keys')}${metric('Updater','Bounded tuning')}${metric('Emergency signer','Pause')}</div>${s.permissions.map(p=>`<p><b>${escape(p.action)}</b><br><span class="warn">${escape(p.boundary)}</span> · request <code>${escape(p.correlationId)}</code></p>`).join('')}<p>Owner recovery restores restricted operations. Development owner keys share one environment.</p><p><a href="demo/proof/operations.json">Denial evidence</a> · <a href="demo/proof/configuration.json">Wallet and policy configuration</a></p>`,
  `<h1>Verified recovery.<br>Inspect every claim.</h1><div class="metrics">${metric('F4 assertions',s.assertions+' passed')}${metric('Settlement attempts','8')}${metric('Restart decision',s.restart.action)}</div><p>Read-only receipt reconciliation: ${escape(s.restart.status)}. No extra signature or maker nonce increment.</p><p><a href="demo/report.md">Full report</a> · <a href="demo/proof/assertions.json">All assertions</a> · <a href="demo/proof-audit.json">Independent proof audit</a> · <a href="demo/demo-manifest.json">Source and artifact hashes</a></p><p class="limits">Local fork, chain 31337. Fixed valuation. Completed-day activity. Shared development custody. No production deployment or profitability claim.</p>`
 ];
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:"><title>Counterweight — recorded demo</title><style>
 *{box-sizing:border-box}body{margin:0;background:#101b27;color:#eef4f7;font:19px/1.5 system-ui,sans-serif}header,footer{padding:18px 5vw;display:flex;justify-content:space-between;gap:20px;background:#152333}header{position:sticky;top:0;z-index:10}header b{letter-spacing:.08em}header span{font-size:14px;color:#94dabf}main{max-width:1260px;margin:auto;padding:35px 5vw;min-height:620px}h1{font-size:44px;line-height:1.12;letter-spacing:-.035em;margin:0 0 22px}.lead{font-size:24px;color:#bcd1df}.metrics{display:flex;gap:16px;margin:25px 0}.metric{flex:1;min-width:0;background:#1c2e3f;border:1px solid #35516a;border-radius:12px;padding:22px}.metric small{display:block;color:#a6c1d3}.metric strong{display:block;font-size:29px;margin-top:8px}.metric p{font-size:17px}.metric code{font-size:14px;overflow-wrap:anywhere}.range{display:flex;justify-content:space-between;border-top:7px solid #68c6a4;padding:12px 0}a{color:#98d7ff}code{font-size:15px}.good{color:#85e0b8}.warn{color:#ffd08c}table{width:100%;border-collapse:collapse;font-size:17px}td,th{text-align:left;padding:9px;border-bottom:1px solid #35516a}details{font-size:14px;margin-top:12px}summary{cursor:pointer;color:#98d7ff}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;background:#0b141e;padding:16px;font-size:12px}.limits{border-left:4px solid #ffd08c;padding-left:16px;color:#cad6df}footer{align-items:center}button{background:#b8f0da;color:#102131;border:0;border-radius:6px;font:inherit;padding:8px 18px;cursor:pointer}button:disabled{opacity:.4}footer small{font-size:12px;color:#c0d0db}.panel[hidden]{display:none}@media(max-width:760px){.metrics{flex-direction:column}h1{font-size:32px}header,footer{flex-wrap:wrap}}
 </style></head><body><header><b>COUNTERWEIGHT</b><span>RECORDED EVIDENCE · local Ethereum fork · no new transactions</span></header><main>${panels.map((p,i)=>`<section class="panel" id="chapter-${i+1}" ${i?'hidden':''}>${p}</section>`).join('')}</main><footer><button id="previous" disabled>← Previous</button><small>Original run ${escape(s.runAt)}<br>Run ${escape(s.runId)} · <span id="position">1 / ${panels.length}</span></small><button id="next">Next →</button></footer><script>
 const panels=[...document.querySelectorAll('.panel')];let index=0;
 function move(delta){index=Math.max(0,Math.min(panels.length-1,index+delta));panels.forEach((p,i)=>p.hidden=i!==index);document.querySelector('#previous').disabled=index===0;document.querySelector('#next').disabled=index===panels.length-1;document.querySelector('#position').textContent=(index+1)+' / '+panels.length;requestAnimationFrame(()=>window.scrollTo(0,0));}
 document.querySelector('#previous').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);document.addEventListener('keydown',event=>{if(event.key==='ArrowRight')move(1);if(event.key==='ArrowLeft')move(-1);});
 </script></body></html>`;
 await writeFile(join(out,'index.html'),html);
 const files=['index.html','RECORDING.md','shared-query.graphql','demo/demo-manifest.json'];
 const hashes={};for(const file of files)hashes[file]=createHash('sha256').update(await readFile(join(out,file))).digest('hex');
 await writeFile(join(out,'recording-kit.json'),JSON.stringify({result:'PASS',mode:'recorded-evidence',runId:s.runId,runAt:s.runAt,sourceProofRevision:s.gitRevision,builderSha256:createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex'),chapters:panels.length,artifactHashes:hashes,videoRecorded:false,uploaded:false},null,2)+'\n');
 console.log('Recording kit ready: '+JSON.stringify(join(out,'index.html')));
}catch(error){
 if(created){await rm(join(out,'index.html'),{force:true});await writeFile(join(out,'failure.json'),JSON.stringify({result:'FAIL',message:'Recording kit preparation failed; no successful presentation.'})+'\n');}
 console.error(error.message==='ARGUMENTS'?'Usage: node scripts/submission/prepare.mjs --out <fresh-directory>':error.code==='EEXIST'?'Output exists; choose a fresh directory.':'Recording kit preparation failed.');process.exitCode=1;
}
